import { styled } from '@mui/material/styles';
import { TableContainer } from '@mui/material';

export const StyledTable = styled(TableContainer)(({ theme }) => ({
	'& .head-row': {
		display: "flex",
		width: "1577px",
		padding: "16px 12px",
		alignItems: "flex-start",
		borderBottom: "1px solid var(--color - border, #E7E7E9)"
	},
	'& .head-name': {
		display: "flex",
		width: "300px",
		alignItems: "center",
		gap: "10px",
		flexShrink: "0",
		color: "var(--color- text, #0D0C22)",
		fontFamily: "Inter",
		fontSize: "16px",
		fontStyle: "normal",
		fontWeight: 600,
		lineHeight: "normal",
		"&.content":{
			color: "var(--color-body, #111215)",
			fontWeight: 400,
		},
	},
	'& .head-role': {
		display: "flex",
		width: "230px",
		alignItems: "center",
		gap: "10px",
		flexShrink: 0,
		color: "var(--color-text, #0D0C22)",
		fontFamily: "Inter",
		fontSize: "16px",
		fontStyle: "normal",
		fontWeight: "600",
		lineHeight: "normal",
		"&.content":{
			fontWeight: 400,
		},
	},
	'& .head-project-manager': {
		display: "flex",
		width: "280px",
		alignItems: "center",
		gap: "10px",
		flexShrink: 0,
		color: "var(--color-text, #0D0C22)",
		fontFamily: "Inter",
		fontSize: "16px",
		fontStyle: "normal",
		fontWeight: "600",
		lineHeight: "normal",
		"&.content":{
			color: "var(--color-body, #111215)",
			fontWeight: 400,
		},
	},
	'& .head-allocation': {
		display: "flex",
		width: "145px",
		alignItems: "center",
		gap: "10px",
		flexShrink: "0",
		color: "var(--color-text, #0D0C22)",
		fontFamily: "Inter",
		fontSize: "16px",
		fontStyle: "normal",
		fontWeight: "600",
		lineHeight: "normal",
		"&.content":{
			color: "var(--color-body, #111215)",
			fontWeight: 400,
		},
	},
	'& .head-date': {
		display: "flex",
		width: "155px",
		alignItems: "center",
		gap: "10px",
		flexShrink: "0",
		color: "var(--color-text, #0D0C22)",
		fontFamily: "Inter",
		fontSize: "16px",
		fontStyle: "normal",
		fontWeight: "600",
		lineHeight: "normal",
		"&.content":{
			color: "var(--color-body, #111215)",
			fontWeight: 400,
		},
	},
	'& .head-status': {
		display: "flex",
		width: "145px",
		alignItems: "center",
		gap: "10px",
		flexShrink: "0",
		color: "var(--color-text, #0D0C22)",
		fontFamily: "Inter",
		fontSize: "16px",
		fontStyle: "normal",
		fontWeight: "600",
		lineHeight: "normal",
		"&.content":{
			color: "var(--color-body, #111215)",
			fontWeight: 400,
		},
	},
	'& .head-project-link': {
		display: "flex",
		width: "142px",
		alignItems: "center",
		gap: "10px",
		flexShrink: "0",
		color: "var(--color-text, #0D0C22)",
		fontFamily: "Inter",
		fontSize: "16px",
		fontStyle: "normal",
		fontWeight: "600",
		lineHeight: "normal",
		"&.content":{
			color: " var(--color-secondary, #4ABD95)",
			fontWeight: 500,
			textDecorationLine: "underline"
		},
	},
	'& .content-row': {

		display: "flex",
		padding: "16px 12px",
		alignItems: "center",
		borderBottom: "1px solid var(--color-border, #E7E7E9)"
	},
	'& .content-text': {
		display: "flex",
		minWidth: "300px",
		alignItems: "center",
		gap: "10px",
		flexShrink: "0",
		color: "var(--color-body, #111215)",
		fontFamily: "Inter",
		fontSize: "16px",
		fontStyle: "normal",
		fontWeight: "400",
		lineHeight: "normal",
	},

	'& .inactive-button-wrap': {
		display: 'flex',
		minWidth: '100px',
		padding: '4px 8px',
		flexDirection: 'row',
		justifyContent: 'flex-start',
		alignItems: 'center',
		gap: 10,
		borderRadius: 100,
		background: 'rgba(110, 109, 122, 0.20)',
	},
	'& .inactive-button-icon': {
		minWidth: '8px',
		height: '8px',
		borderRadius: '50%',
		backgroundColor: '#6E6D7A',
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
	},
	'& .inactive-button-text': {
		color: '#6E6D7A',
	},
	'& .active-button-wrap': {
		display: 'flex',
		minWidth: '100px',
		padding: '4px 8px',
		flexDirection: 'row',
		justifyContent: 'flex-start',
		alignItems: 'center',
		gap: 10,
		borderRadius: 100,
		background: 'rgba(83, 205, 130, 0.20)',
	},
	'& .active-button-icon': {
		minWidth: '8px',
		height: '8px',
		borderRadius: '50%',
		backgroundColor: '#53CD82',
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
	},
	'& .active-button-text': {
		color: '#53CD82',
	},
	'& custom-paper': {
		color: 'pink',
	},
	" & .divider": {
		width: "100%",
		height: 1,
		backgroundColor: "#E7E7E9"
	},
	[theme.breakpoints.down('sm')]: {},
}));
